# Use official Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose Kafka port if needed for internal debugging (optional)
# EXPOSE 9092

# Run producer script
CMD ["python", "main.py"]
